added more information
JSPrismarine/Docs pull request #1
Opened 2021-01-26 06:55 UTC by Jakobg1215

Added more information for player-events.md, block-events.md, and chat-events.md!

2021-01-28 02:11 UTC, Bavfalcon9 requested changes

2021-01-28 02:11 UTC, Bavfalcon9 commented on events/block-events.md
> +this.api.getEventManager()
There is no need for this change.

2021-01-28 02:11 UTC, Bavfalcon9 commented on events/chat-events.md
> +
Examples should be embedded in events name, not separate.

2021-01-28 02:11 UTC, Bavfalcon9 commented on SUMMARY.md
> +## LoggerBuilder
Logger isn't a builder, but a utility, possible naming convention change.

2021-01-28 16:07 UTC, Jakobg1215 commented on events/chat-events.md
> +
what? It is the same as events/block-events.md.

2021-01-28 16:08 UTC, Jakobg1215 commented on events/block-events.md
> +this.api.getEventManager()
Just looks nicer and adds types.

2021-02-10 22:14 UTC, filfat requested changes

2021-02-10 22:14 UTC, filfat commented on logger/warn-logger.md
> +this.api.getLogger().warn("This might not work but okay.");
This should be used to warn the user. A better example would be `warn("Database is missing, creating a new one...")`

2021-02-10 22:14 UTC, filfat commented on logger/error-logger.md
> +log any errors to the console.
`errors` -> `error`.

2021-02-10 22:14 UTC, filfat commented on logger/error-logger.md
> +this.api.getLogger().error("Something when wrong here!");
"went" is misspelt here.

2021-02-10 22:14 UTC, filfat commented on events/player-events.md
> +### Prevent any player to fly
Grammar check please.

Should be "Prevent any player from flying".

2021-02-10 22:14 UTC, filfat commented on events/player-events.md
> +Fired when a player changes there gamemode.
Their* (there is a specified position while their is a possessive statement).

2021-02-10 22:14 UTC, filfat commented on events/player-events.md
> +Fired when a player starts to sprint.
Replace with `Fired when a player toggles spriting`. Since it'll be fired when the player starts **or** stops spriting.

2021-02-10 22:14 UTC, filfat commented on events/player-events.md
> +Fired when a player starts to fly.
Replace with `Fired when a player toggles flying`. Since it'll be fired when the player starts or stops flying.

2021-02-10 22:14 UTC, filfat commented on events/player-events.md
> +Fired when a player moves in the server.
Remove `in the server`.

2021-02-10 22:14 UTC, filfat commented on events/chat-events.md
> +### Prevent any chat with capital letters
`chat` -> `chat message`.

2021-02-10 22:14 UTC, filfat commented on events/chat-events.md
> +        this.api.getLogger().info("Messages can not have capital letters!");
Replace the log with a message to the user triggering the event.

2021-02-10 22:26 UTC, filfat requested changes

2021-02-10 22:26 UTC, filfat commented on events/player-events.md
> +Fired when a player add or removes there operator status.
their*

2021-02-10 22:26 UTC, filfat commented on logger/warn-logger.md
> +log any warnings to the console.
warning*. Singular.

2021-02-10 22:30 UTC, merged